# NumPy 
Pertemuan Ke-4 Materi Introduction Python for Data science

## Introduction NumPy
NumPy (Python Numerik) adalah ekstensi open source dari Python Numerical komputasi. NumPy dari tahun 2005 dan membentuk semacam kode sumber terbuka dan dipelihara dan dikembangkan oleh banyak kolaborator bersama-sama.NumPy API digunakan secara luas di Pandas, SciPy, Matplotlib, scikit-learn, scikit-image dan sebagian besar paket ilmu data dan Python ilmiah lainnya.

## importing NumPy

In [2]:
import numpy as np 
np.__version__

'1.20.3'

In [6]:
def pythonsum (n):
    a=b=list(range(n))
    c=[]
    for i in range(len(a)):
        x=a[i]**2
        y=b[i]**3
        c.append(x+y)
    return c


In [7]:
c=pythonsum(10)
print(c)

[0, 2, 12, 36, 80, 150, 252, 392, 576, 810]


In [8]:
def numpysum(n):
    a=np.arange(n)**2
    b=np.arange(n)**3
    c=a+b
    return c

In [9]:
x=numpysum(10)
print(x)

[  0   2  12  36  80 150 252 392 576 810]


In [18]:
from datetime import datetime
size =100
start=datetime.now()
c=pythonsum(size)
delta=datetime.now()-start
print('The last 2 element of the sum is ', c[98:])
print("PythonSum elapsed time in microseconds", delta.microseconds)

The last 2 element of the sum is  [950796, 980100]
PythonSum elapsed time in microseconds 971


In [23]:
start = datetime.now()
c = numpysum(size)
delta = datetime.now() - start
print("The last 2 elements of the sum", c[98:])
print("NumPySum elapsed time in microseconds", delta.microseconds)

The last 2 elements of the sum [950796 980100]
NumPySum elapsed time in microseconds 993


## Array
   array merupakan struktur data pusat dari library NumPy. Array adalah kisi nilai dan berisi informasi tentang data mentah, cara menemukan elemen, dan cara menafsirkan elemen. Array dapat diindeks oleh tupel bilangan non-negatif, dengan boolean, dengan array lain, atau dengan bilangan bulat. Rank array adalah jumlah dimensi

In [24]:
np.array([1, 2, 3])

array([1, 2, 3])

In [29]:
array1=np.arange(10000)

In [26]:
array2=list(np.arange(100))

In [27]:
print(array2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [30]:
print(array1)

[   0    1    2 ... 9997 9998 9999]


## membuat NDArray

In [31]:
my_list = list(range(5))
my_list

[0, 1, 2, 3, 4]

In [32]:
array_1 = np.array(my_list)
print(type(array_1))
array_1


<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4])

In [40]:
print(np.arange(4))
print(np.arange(0,10,2)) # 0 sampai 10 dengan jarak 2

[0 1 2 3]
[0 2 4 6 8]


In [41]:
print(np.arange(2,29,5))

[ 2  7 12 17 22 27]


## add, sort, remove

In [42]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr)

[1 2 3 4 5 6 7 8]


In [43]:
arr = np.append(arr, [9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [44]:
# menghapus index 1 
np.delete(arr, 1)

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [46]:
data = np.sort(arr)
print(data)

[1 2 3 4 5 6 7 8]


## Multi Dimension Array

In [47]:
multi_list = [[0, 1, 2, 3], [10, 11, 12,13]]
print(type(multi_list))
multi_list

<class 'list'>


[[0, 1, 2, 3], [10, 11, 12, 13]]

In [48]:
a = np.array(multi_list)
print(type(a))
a

<class 'numpy.ndarray'>


array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

## ndim , shape and size

In [49]:
arr_1 = np.array([2, 1, 5, 3, 7, 4, 6, 8])  # 1 dimensi
print(arr_1)

[2 1 5 3 7 4 6 8]


In [50]:
arr_1.ndim # Untuk mengetahui jumlah dimensi pada data menggunakan ndim


1

In [51]:
arr_1.shape # Array a memiliki shape, yaitu panjang array pada 1-dimensi array.


(8,)

In [60]:
arr_1.size

8

In [53]:
a.shape 

(2, 4)

In [54]:
a.size

8

In [55]:
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [58]:
arr_2=np.array([
    1, 2, 3, 4, 5, 6
])
arr_2

array([1, 2, 3, 4, 5, 6])

In [59]:
arr_2.size

6

In [61]:
a.ndim

2

In [62]:
array_3d=np.array([[[0, 1, 2, 3],
                     [4, 5, 6, 7]],

                    [[0, 1, 2, 3],
                     [4, 5, 6, 7]],

                    [[0, 1, 2, 3],
                    [4, 5, 6, 7]]])
print(array_3d)


[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [63]:
array_3d.ndim

3

In [64]:
array_3d.size

24

In [65]:
array_3d.shape

(3, 2, 4)

#### Mengganti Elemen Array 

In [66]:
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [67]:
a[1,3]= -1
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, -1]])

## Sorting Array

In [68]:
data = np.array([[4, 1, 0, 5],[1, 5, 3, 4]])
data

array([[4, 1, 0, 5],
       [1, 5, 3, 4]])

In [72]:
data.sort(axis=1)
print(data)

[[0 1 4 5]
 [1 3 4 5]]


In [75]:
data = np.array([[4, 1, 0, 5],[1, 5, 3, 4]])
# menambahkan parameter axis =0 
print(data)
print("sebelum di sort axis=0")
print(10*"=====")
data.sort(axis=0)
print(data)

[[4 1 0 5]
 [1 5 3 4]]
sebelum di sort axis=0
[[1 1 0 4]
 [4 5 3 5]]


In [76]:
dtype = [('name', 'S10'), ('height', float), ('age', int)]  ##  name type string , heigh type float , age type int
values = [('Arthur', 1.8, 41), 
          ('Lancelot', 1.9, 38),
          ('Galahad', 1.7, 38)]
a = np.array(values, dtype=dtype) # create a structured array
print(a)

[(b'Arthur', 1.8, 41) (b'Lancelot', 1.9, 38) (b'Galahad', 1.7, 38)]


In [77]:
np.array

<function numpy.array>

In [78]:
x = np.sort(a, order='name')  
print(x)

[(b'Arthur', 1.8, 41) (b'Galahad', 1.7, 38) (b'Lancelot', 1.9, 38)]


In [80]:
np.sort(a, order=('age', 'height') )   

array([(b'Galahad', 1.7, 38), (b'Lancelot', 1.9, 38),
       (b'Arthur', 1.8, 41)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i4')])

In [81]:
values[1]

('Lancelot', 1.9, 38)

In [82]:
values[0][1]

1.8

## Zeroes

In [83]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [85]:
np.ones(2,np.uint16)

array([1, 1], dtype=uint16)

In [90]:
# Fungsi kosong membuat larik yang konten awalnya acak dan bergantung pada status memori.
np.empty(8) # lakukan perubahan parameter

array([0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
       0.0000000e+000, 7.2528837e-321, 1.3623213e-311, 1.3623213e-311])

In [91]:
dzero = np.zeros((2,2,2))
print(dzero)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [92]:
dzero.shape

(2, 2, 2)

In [93]:
dzero.ndim

3

In [94]:
zeros_ndarray = np.zeros((3, 6))
zeros_ndarray

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [95]:
zeros_ndarray.shape

(3, 6)

In [96]:
zeros_ndarray.ndim

2

In [97]:
ones_array = np.ones(10)
ones_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [98]:
empty_array = np.empty((4, 3, 2))
empty_array

array([[[6.23042070e-307, 3.56043053e-307],
        [1.60219306e-306, 7.56571288e-307],
        [1.89146896e-307, 1.37961302e-306]],

       [[1.05699242e-307, 8.01097889e-307],
        [1.78020169e-306, 7.56601165e-307],
        [1.02359984e-306, 1.24610383e-306]],

       [[9.34603679e-307, 8.34423068e-308],
        [8.06610070e-308, 8.34424342e-308],
        [1.02360256e-306, 2.22523004e-306]],

       [[1.78021527e-306, 6.23059726e-307],
        [1.33511562e-306, 6.89805151e-307],
        [1.11261909e-306, 1.42410974e-306]]])

In [99]:
empty_array.ndim

3

## Reshape

In [101]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [102]:
b = a.reshape(2,3)
print(b)

[[0 1 2]
 [3 4 5]]


In [105]:
c = a.reshape((3,2))
print(c)

[[0 1]
 [2 3]
 [4 5]]


In [106]:
x = np.arange(5)
print(x)
x1 = x.reshape(2,3)
print(x)

[0 1 2 3 4]


ValueError: cannot reshape array of size 5 into shape (2,3)

In [107]:
a = np.arange(6).reshape((3, 2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [109]:
a = np.array([[1,2,3], [4,5,6]])
np.reshape(a, 6)


array([1, 2, 3, 4, 5, 6])

## Mengkonversi 1D ke 2D

In [4]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [111]:
# menambahkan menggunakan np.newaxis 
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [5]:
 # meng convert 1 D array ke row vector dengan insert ke axis ,1 dimensi
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [6]:

col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [7]:
b = np.expand_dims(a, axis=1)
b.shape
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [8]:
c = np.expand_dims(a, axis=0)
c.shape
print(c)

[[1 2 3 4 5 6]]


## Index dan Slice

In [9]:
data=np.array([1, 2, 3])
data

array([1, 2, 3])

In [10]:
print(data[0])
print(data[1])

1
2


In [13]:
print(data[0:2])

[1 2]


In [14]:
print(data[1:])

[2 3]


In [15]:
print(data[:3])

[1 2 3]


In [16]:
print(data[-2:])

[2 3]


In [17]:
arr=np.array([1, 2, 3, 4, 5])
print(arr[:])
print((arr[1:]))
print((arr[2:4]))
print(repr(arr[:-1])) # array([1, 2, 3, 4])
print(repr(arr[-2:])) # array([4, 5])

[1 2 3 4 5]
[2 3 4 5]
[3 4]
array([1, 2, 3, 4])
array([4, 5])


In [18]:
a = np.array([[1 , 2, 3, 4],
              [5, 6, 7, 8], 
              [9, 10, 11, 12]
             ])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
a.dtype

dtype('int32')

In [20]:
print(type(a))

<class 'numpy.ndarray'>


In [21]:
print(a[a<5])

[1 2 3 4]


In [25]:
lima_atas= a>=5
print(a[lima_atas])

[ 5  6  7  8  9 10 11 12]


In [26]:
divisible_by_2 = a[a%2==0]

print(divisible_by_2)

[ 2  4  6  8 10 12]


In [27]:
c = a[(a > 2) & (a < 11)]

print(c)

[ 3  4  5  6  7  8  9 10]


## Membuat Array Dari Data Yang Sudah Ada
    slicing indexing
    np.vstack()
    np.hstack()
    np.hsplit()
    .view()
    .copy()

In [28]:
arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [29]:
a_1 = np.array([[1, 1],
                [2, 2]])
a_2 = np.array([[3, 3],
                [4, 4]])

In [30]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [31]:
a = np.array([1,2, 3])
b = np.array([21, 32, 43])

np.vstack((a,b))

array([[ 1,  2,  3],
       [21, 32, 43]])

In [33]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
print(a)
print(5*"<><><>")
print(b)
np.vstack((a,b))

[[1]
 [2]
 [3]]
<><><><><><><><><><><><><><><>
[[2]
 [3]
 [4]]


array([[1],
       [2],
       [3],
       [2],
       [3],
       [4]])

In [34]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [6]:
arrsplit = np.array([[1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
                     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,24]])
print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [7]:
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [8]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [9]:
b=a.view()

In [10]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
c=a.copy()

In [12]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
c[1,2]=0

In [14]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  0,  8],
       [ 9, 10, 11, 12]])

In [15]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Copying 

In [16]:
x = [0,1]
y = [9,8]
z = x

print(x)
z[0] = 5 
print(x)

[0, 1]
[5, 1]


In [17]:
p = y.copy()
p[0] = 6 
print(y)  # tidak berubah 
print(p)

[9, 8]
[6, 8]


In [18]:
a = np.array([0, 1])
b = np.array([9, 8])
c = a
print('Array a: {}'.format(repr(a)))
c[0] = 5
print('Array a: {}'.format(repr(a)))

d = b.copy()
d[0] = 6
print('Array b: {}'.format(repr(b)))
print('Array b: {}'.format(repr(d)))

Array a: array([0, 1])
Array a: array([5, 1])
Array b: array([9, 8])
Array b: array([6, 8])


## Basic Array Operations

In [21]:
a = np.array([1, 2, 3, 4])
b = np.array([[1, 1], [2, 2]])

In [22]:
b.sum(axis=0)

array([3, 3])

In [23]:
b.sum(axis=1)

array([2, 4])

In [24]:
data = np.array([1,2])
data

array([1, 2])

In [28]:
ones = np.ones(100, np.uint16)
print(ones)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [29]:
data + ones

ValueError: operands could not be broadcast together with shapes (2,) (100,) 

In [27]:
data * data 

array([1, 4])

## Broadcasting
NumPy memahami bahwa perkalian harus terjadi dengan setiap sel. Konsep itu disebut broadcasting. Broadcasting adalah mekanisme yang memungkinkan NumPy untuk melakukan operasi pada array dari berbagai bentuk. Dimensi array Anda harus kompatibel, misalnya, ketika dimensi kedua array sama, atau ketika salah satunya adalah 1. Jika dimensi tidak kompatibel, Anda akan mendapatkan kesalahan nilai.


In [30]:
print(data)
print(data * 2)

[1 2]
[2 4]


## Function

### zeroes

In [31]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)

[[0. 0.]
 [0. 0.]]


### ones

In [32]:
b = np.ones((1,2))    # Create an array of all ones
print(b)

[[1. 1.]]


### full

In [33]:
c = np.full((2,2), 7)  # Create a constant array
print(c) 

[[7 7]
 [7 7]]


### eye

In [34]:
d=np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


### random

In [36]:
print(np.random.seed(0))

None


In [41]:
print(np.random.randint(10))

7


In [43]:
random_arr=np.random.randint(10,100,6) # print random int sebanyak 6 antara 10 -100
print(random_arr)

[98 98 22 68 75 49]


In [50]:
np.random.seed(0)
random_arr = np.random.randint(5, high=20,
                               size=(2, 2)) ## randint(low, high=None, size=None, dtype=int)

print(repr(random_arr))

array([[17, 10],
       [ 5,  8]])


In [55]:
# New seed
np.random.seed(1)
print(np.random.seed(1))
random_arr = np.random.randint(3, high=100,
                               size=(2, 2))
print(repr(random_arr))


None
array([[40, 15],
       [75, 12]])


## more array operation

In [56]:
aA = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(aA)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [57]:
aA.sum()

4.8595784

In [58]:
aA.min()

0.05093587

In [60]:
aA.min(axis=1)

array([0.17296777, 0.05093587, 0.12697628])

In [61]:
aA.std(
)

0.21392120766089617

In [62]:
dataA=aA.min(axis=1)
print(dataA)

[0.17296777 0.05093587 0.12697628]


In [63]:
print(dataA.argmin()) # posisi indeks

1


In [64]:
print(dataA.argmax())

0


## save array to file

In [65]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [66]:
np.save('myarraytest.npy',A)

In [67]:
responsefile=np.load('myarraytest.npy')
print(responsefile)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


## Training

In [69]:
lat_arr=np.array([
    [0, 72, 3],
    [1, 3, -60],
    [-3, -2, 4]
])
lat_arr

array([[  0,  72,   3],
       [  1,   3, -60],
       [ -3,  -2,   4]])

In [70]:
np.save('latihanarray.npy',lat_arr)

In [71]:
resfile=np.load('latihanarray.npy')
print(resfile)

[[  0  72   3]
 [  1   3 -60]
 [ -3  -2   4]]


In [72]:
print(resfile.min())
print(resfile.max())

-60
72


In [73]:
print(repr(resfile.min(axis=0)))
print(repr(resfile.max(axis=0)))

print(repr(resfile.max(axis=1)))
print(repr(resfile.min(axis=1)))

array([ -3,  -2, -60])
array([ 1, 72,  4])
array([72,  3,  4])
array([  0, -60,  -3])


## studi kasus

10 buah botol minum akan dibuat untuk menyimpan air dengan jari2 dan tinggi yang berbeda - beda . 
Besaran jari2 dan tinggi botol adalah bilang bulat kisaran 7 sampai dengan 20 cm . 

Temukan : 

1. Volume air yang dapat disimpan di setiap botol 
2. Total volume air yang tersimpan dalam semua botol 
3. Botol mana yang volume air terkecil dan temukan volumenya 
4. Botol mana yang menampung volume air terbesar dan temukan volume airnya . 
5. Rata-rata volume yang dapat di tampung di tiap botol 

In [106]:

dtbotol=np.random.randint(7, 20, 20)
print(dtbotol)

[19  9 11 17  8 14 15  9 17 16 15 14  8 13 15 17 12 16 16 16]


In [107]:
dtbotol.resize(10,2)
print(dtbotol)

[[19  9]
 [11 17]
 [ 8 14]
 [15  9]
 [17 16]
 [15 14]
 [ 8 13]
 [15 17]
 [12 16]
 [16 16]]


In [108]:
volume = (np.pi*dtbotol[:,1]**2)*dtbotol[:,0]
print(volume)
totalvolume=volume.sum()
print("Total Volume : ", totalvolume)

[ 4834.91109387  9987.12304576  4926.01728083  3817.03507411
 13672.21122842  9236.28240155  4247.43326765 13618.80415331
  9650.97263183 12867.9635091 ]
Total Volume :  86858.7536864506


In [109]:
volume.argmin() # 
volume[volume.argmin()]

3817.0350741115985

In [110]:
volume.argmax()
volume[volume.argmax()]

13672.21122842278

In [111]:
idxBotolKecil = volume.argmin()
volumeBotolKecil = volume[idxBotolKecil]
print(f"Botol Terkecil Pada Botol index : {idxBotolKecil} volume {volumeBotolKecil}")
idxBotolBesar = volume.argmax()
volumeBotolBesar = volume[idxBotolBesar]
print(f"Botol Terkecil Pada Botol index : {idxBotolBesar} volume {volumeBotolBesar}")


Botol Terkecil Pada Botol index : 3 volume 3817.0350741115985
Botol Terkecil Pada Botol index : 4 volume 13672.21122842278


## Np read csv

In [113]:
import csv
data = []

with open('data/MER_T07_02A.csv', 'r') as csvfile:
    file_reader = csv.reader(csvfile, delimiter=',')
    for row in file_reader:
        data.append(row)
        
data = np.array(data)

FileNotFoundError: [Errno 2] No such file or directory: 'data/MER_T07_02A.csv'

## Matriks

In [1]:
import numpy as np

In [3]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.randint((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[2 0]


## Matriks aritmatika

In [6]:
data=np.array([
    [1,2],
    [3,4]
])
data

array([[1, 2],
       [3, 4]])

In [7]:
msatu=np.ones([2,2])

In [8]:
print(data+msatu)

[[2. 3.]
 [4. 5.]]


In [9]:
msatu_kolom=np.ones([1,2])

In [11]:
print(data+msatu_kolom)

[[2. 3.]
 [4. 5.]]


In [12]:
data1=np.array([
    [1, 2],
    [3, 4],
    [5, 6],
])
print(data1)

[[1 2]
 [3 4]
 [5 6]]


In [13]:
print(data1+msatu_kolom)

[[2. 3.]
 [4. 5.]
 [6. 7.]]


## Dot product

In [15]:
np.dot?

In [17]:
np.dot(3,4)

12

In [18]:
a = np.arange(3*4*5*6).reshape((3,4,5,6)) 
print(a)

[[[[  0   1   2   3   4   5]
   [  6   7   8   9  10  11]
   [ 12  13  14  15  16  17]
   [ 18  19  20  21  22  23]
   [ 24  25  26  27  28  29]]

  [[ 30  31  32  33  34  35]
   [ 36  37  38  39  40  41]
   [ 42  43  44  45  46  47]
   [ 48  49  50  51  52  53]
   [ 54  55  56  57  58  59]]

  [[ 60  61  62  63  64  65]
   [ 66  67  68  69  70  71]
   [ 72  73  74  75  76  77]
   [ 78  79  80  81  82  83]
   [ 84  85  86  87  88  89]]

  [[ 90  91  92  93  94  95]
   [ 96  97  98  99 100 101]
   [102 103 104 105 106 107]
   [108 109 110 111 112 113]
   [114 115 116 117 118 119]]]


 [[[120 121 122 123 124 125]
   [126 127 128 129 130 131]
   [132 133 134 135 136 137]
   [138 139 140 141 142 143]
   [144 145 146 147 148 149]]

  [[150 151 152 153 154 155]
   [156 157 158 159 160 161]
   [162 163 164 165 166 167]
   [168 169 170 171 172 173]
   [174 175 176 177 178 179]]

  [[180 181 182 183 184 185]
   [186 187 188 189 190 191]
   [192 193 194 195 196 197]
   [198 199 200 201 202 203]


In [19]:
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))
print(b)

[[[[359 358 357]
   [356 355 354]
   [353 352 351]
   [350 349 348]
   [347 346 345]
   [344 343 342]]

  [[341 340 339]
   [338 337 336]
   [335 334 333]
   [332 331 330]
   [329 328 327]
   [326 325 324]]

  [[323 322 321]
   [320 319 318]
   [317 316 315]
   [314 313 312]
   [311 310 309]
   [308 307 306]]

  [[305 304 303]
   [302 301 300]
   [299 298 297]
   [296 295 294]
   [293 292 291]
   [290 289 288]]]


 [[[287 286 285]
   [284 283 282]
   [281 280 279]
   [278 277 276]
   [275 274 273]
   [272 271 270]]

  [[269 268 267]
   [266 265 264]
   [263 262 261]
   [260 259 258]
   [257 256 255]
   [254 253 252]]

  [[251 250 249]
   [248 247 246]
   [245 244 243]
   [242 241 240]
   [239 238 237]
   [236 235 234]]

  [[233 232 231]
   [230 229 228]
   [227 226 225]
   [224 223 222]
   [221 220 219]
   [218 217 216]]]


 [[[215 214 213]
   [212 211 210]
   [209 208 207]
   [206 205 204]
   [203 202 201]
   [200 199 198]]

  [[197 196 195]
   [194 193 192]
   [191 190 189]
   [188 1

In [22]:
np.dot(a, b)[2,3,2,1,2,2]

499128

In [23]:
sum(a[2,3,2,:] * b[1,2,:,2])

499128

## Matriks Indexing

In [24]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)

[[1 2]
 [3 4]
 [5 6]]


In [25]:
print(data[0,1])

2


In [26]:
print(data[1:3])

[[3 4]
 [5 6]]


In [27]:
print(data[0:2,0])

[1 3]


In [28]:
print((data[:]))


[[1 2]
 [3 4]
 [5 6]]


In [30]:
print(data[:, -1]) # -1 kanan
xdata = data[:, -1]
xdata.ndim  # 1 dimensi


[2 4 6]


1

In [31]:
print(data[:, 1:]) # -1 kanan
xdata = data[:, 1:]
xdata.ndim  # 2 dimensi

[[2]
 [4]
 [6]]


2

In [32]:
print(data[:, :]) 


[[1 2]
 [3 4]
 [5 6]]


In [36]:
print(data[:, 0:1]) 
print(3*('==='))
print(data[:, 1:2]) 
print(3*('==='))
print(data[:, 1:]) 
print(3*('==='))
print((data[0:2,:]))

[[1]
 [3]
 [5]]
[[2]
 [4]
 [6]]
[[2]
 [4]
 [6]]
[[1 2]
 [3 4]]


In [37]:
print(repr(data[0:1, 1:]))
print(repr(data[0:2,:]))
print(repr(data[0:2, 1:]))
print(repr(data[1, 1:]))

array([[2]])
array([[1, 2],
       [3, 4]])
array([[2],
       [4]])
array([4])


In [38]:
np_m = np.arange(1,17)
np_m 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [39]:
np4x4 = np_m.reshape(4,4)
np4x4 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [40]:
# baris 1 dan kolom 2:4 
npa = np4x4[1,2:4]
print(npa)
print(repr(npa))
print(5*"=======")
# semua baris, hanya kolom 1 
npb = np4x4[:,1] 
print(npb)
print(repr(npb))

[7 8]
array([7, 8])
[ 2  6 10 14]
array([ 2,  6, 10, 14])


In [41]:
# baris 2 sampai akhir dan kolom 2 sampai akhir 
npc = np4x4[2: , 2:] 
print(npc) 
print(5*"-")
# baris 1, step 2  dan  dari 0  step 2 
npd = np4x4[1::2, ::2] 
print(npd )

[[11 12]
 [15 16]]
-----
[[ 5  7]
 [13 15]]


## Latihan 
latihan indexing

buat 2 array dengan shape (3, 4)
[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  
 menggunakan slicing untuk mendaptkan subarray yang terdiri dari 2 baris pertama
 dan kolom 1 dan 2; b adalah array bentuk berikut (2, 2):
 
 [[2 3]
  [6 7]]

In [42]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [43]:
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [44]:
print(a[0, 1])   
b[0, 0] = 77     
print(b)
print(a[0, 1])

2
[[77  3]
 [ 6  7]]
77


In [45]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print((arr[:]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [46]:
print((arr[1:]))

[[4 5 6]
 [7 8 9]]


In [47]:
print(repr(arr[:, -1]))
print(repr(arr[:, 1:]))
print(repr(arr[0:1,:]))
print(repr(arr[0:1, 1:]))
print(repr(arr[0:2, 1:]))

array([3, 6, 9])
array([[2, 3],
       [5, 6],
       [8, 9]])
array([[1, 2, 3]])
array([[2, 3]])
array([[2, 3],
       [5, 6]])


## Matriks Aggregation

In [48]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)

[[1 2]
 [3 4]
 [5 6]]


In [49]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [50]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


## transpose dan reshape

In [51]:
data = np.array([[1, 2], [3, 4], [5, 6]])
print(data)
print(data.transpose())

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [52]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [53]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [54]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [57]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


In [58]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


## Flatten N-Dimentional Array

In [60]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [61]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])